image: curlimages/curl:latest

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data branch=master "https://git.pc-web.at/api/v4/projects/$CI_PROJECT_ID/packages/composer"'
